@startuml

title __IMPLEMENTACION's Class Diagram__\n

  namespace ar.edu.ort {
    namespace implementacion {
      class ar.edu.ort.implementacion.ProductoCompuesto {
          - productos : ArrayList<IPrecio>
          + ProductoCompuesto()
          + addProducto()
          + getImporteTotal()
          + getProductos()
          + removeProducto()
      }
    }
  }
  

  namespace ar.edu.ort {
    namespace implementacion {
      class ar.edu.ort.implementacion.ProductoPeso {
          - categoria : String
          - nombre : String
          - peso : double
          - precioPorPeso : double
          + ProductoPeso()
          + getCategoria()
          + getImporteTotal()
          + getNombre()
          + getPeso()
          + getPrecioPorPeso()
          + setCategoria()
          + setNombre()
          + setPeso()
          + setPrecioPorPeso()
      }
    }
  }
  

  namespace ar.edu.ort {
    namespace implementacion {
      class ar.edu.ort.implementacion.ProductoUnitario {
          - cantidad : int
          - categoria : String
          - nombre : String
          - precio : double
          + ProductoUnitario()
          + getCantidad()
          + getCategoria()
          + getImporteTotal()
          + getNombre()
          + getPrecio()
          + setCantidad()
          + setCategoria()
          + setNombre()
          + setPrecio()
      }
    }
  }
  

  ar.edu.ort.implementacion.ProductoCompuesto .up.|> ar.edu.ort.base.IPrecio
  ar.edu.ort.implementacion.ProductoPeso .up.|> ar.edu.ort.base.IPrecio
  ar.edu.ort.implementacion.ProductoUnitario .up.|> ar.edu.ort.base.IPrecio


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
